# config/cucumber.yml
verbose     : cucumber_api_verbose=true
web_chrome  : --tags @web_chrome PLATFORM_NAME=browser BROWSER=chrome HOST=web
web_firefox : --tags @web_firefox PLATFORM_NAME=browser BROWSER=firefox HOST=web
api         : --tags @api PLATFORM_NAME=api
android     : --tags @android PLATFORM_NAME=android